import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";
import { STALENESS_THRESHOLD_MS } from "@/lib/offline-cache";

/**
 * Service-worker behavioural unit test.
 *
 * Loading the SW module under jsdom requires faking the worker-global
 * surface (`self`, `caches`, `crypto.subtle.digest`, the `clients`
 * registry). We synthesise a minimal harness, register the listener-
 * collecting `self.addEventListener`, then invoke `src/sw.ts` so its
 * top-level `self.addEventListener("install" / "activate" / "fetch")`
 * registrations fire into our captured handlers.
 *
 * The bundled SW (`public/sw.js`) is generated by `scripts/build-sw.mjs`
 * via esbuild — that pipeline is exercised by `npm run build`. This unit
 * test isolates the policy decisions (24h TTL, cache versioning,
 * never-cache prefix list) from the bundler.
 */

interface CapturedListeners {
  install: ((event: ExtendableEvent) => void)[];
  activate: ((event: ExtendableEvent) => void)[];
  fetch: ((event: FetchEvent) => void)[];
}

const listeners: CapturedListeners = {
  install: [],
  activate: [],
  fetch: [],
};

// Minimal Cache implementation.
class FakeCache {
  store = new Map<string, Response>();

  async match(key: string | Request): Promise<Response | undefined> {
    const k = typeof key === "string" ? key : key.url;
    const r = this.store.get(k);
    return r ? r.clone() : undefined;
  }

  async put(key: string | Request, response: Response): Promise<void> {
    const k = typeof key === "string" ? key : key.url;
    this.store.set(k, response.clone());
  }

  async addAll(_urls: string[]): Promise<void> {
    // No-op for tests; pre-cache is best-effort.
  }
}

const cacheRegistry = new Map<string, FakeCache>();

const fakeCaches = {
  async open(name: string): Promise<FakeCache> {
    let c = cacheRegistry.get(name);
    if (!c) {
      c = new FakeCache();
      cacheRegistry.set(name, c);
    }
    return c;
  },
  async keys(): Promise<string[]> {
    return Array.from(cacheRegistry.keys());
  },
  async delete(name: string): Promise<boolean> {
    return cacheRegistry.delete(name);
  },
  async match(): Promise<undefined> {
    return undefined;
  },
};

const fakeClients = {
  async matchAll(): Promise<{ postMessage: (m: unknown) => void }[]> {
    return [];
  },
  async claim(): Promise<void> {},
};

let originalSelf: unknown;
let originalCaches: unknown;
let originalCrypto: unknown;

beforeAll(async () => {
  originalSelf = (globalThis as { self?: unknown }).self;
  originalCaches = (globalThis as { caches?: unknown }).caches;
  originalCrypto = globalThis.crypto;

  const fakeSelf = {
    addEventListener(type: keyof CapturedListeners, handler: unknown) {
      if (type in listeners) {
        listeners[type].push(handler as never);
      }
    },
    clients: fakeClients,
    location: { origin: "https://app.example" },
  };

  Object.defineProperty(globalThis, "self", {
    configurable: true,
    value: fakeSelf,
  });
  Object.defineProperty(globalThis, "caches", {
    configurable: true,
    value: fakeCaches,
  });

  // Ensure crypto.subtle.digest works in jsdom.
  if (!globalThis.crypto || !globalThis.crypto.subtle) {
    const { webcrypto } = await import("node:crypto");
    Object.defineProperty(globalThis, "crypto", {
      configurable: true,
      value: webcrypto,
    });
  }

  // Loading the SW source registers all three listeners on our fakeSelf.
  await import("@/sw");
});

afterAll(() => {
  if (originalSelf !== undefined) {
    Object.defineProperty(globalThis, "self", {
      configurable: true,
      value: originalSelf,
    });
  }
  if (originalCaches !== undefined) {
    Object.defineProperty(globalThis, "caches", {
      configurable: true,
      value: originalCaches,
    });
  } else {
    delete (globalThis as { caches?: unknown }).caches;
  }
  if (originalCrypto !== undefined) {
    Object.defineProperty(globalThis, "crypto", {
      configurable: true,
      value: originalCrypto,
    });
  }
});

/**
 * Helper: invoke an ExtendableEvent-style handler with a `waitUntil`
 * promise capture.
 */
async function triggerLifecycle(
  handlers: ((event: ExtendableEvent) => void)[],
): Promise<void> {
  for (const handler of handlers) {
    const promises: Promise<unknown>[] = [];
    const event = {
      waitUntil: (p: Promise<unknown>) => promises.push(p),
    } as unknown as ExtendableEvent;
    handler(event);
    await Promise.all(promises);
  }
}

describe("service worker — lifecycle", () => {
  it("registers install, activate, and fetch handlers", () => {
    expect(listeners.install.length).toBeGreaterThan(0);
    expect(listeners.activate.length).toBeGreaterThan(0);
    expect(listeners.fetch.length).toBeGreaterThan(0);
  });

  it("activate evicts old cache versions and keeps the current one", async () => {
    // Pre-populate the registry with caches from old + current versions.
    await fakeCaches.open("cm-static-v1-dev");
    await fakeCaches.open("cm-data-v1-dev");
    await fakeCaches.open("cm-static-v1-old");
    await fakeCaches.open("cm-data-v1-old");
    await fakeCaches.open("unrelated-cache");

    await triggerLifecycle(listeners.activate);

    const remaining = await fakeCaches.keys();
    // The "current" caches are named with BUILD_ID === "dev" because the
    // SW source is loaded directly (not via esbuild's --define). The
    // eviction policy must keep those + leave unrelated caches alone.
    expect(remaining).toContain("cm-static-v1-dev");
    expect(remaining).toContain("cm-data-v1-dev");
    expect(remaining).toContain("unrelated-cache");
    expect(remaining).not.toContain("cm-static-v1-old");
    expect(remaining).not.toContain("cm-data-v1-old");
  });

  it("install attempts pre-cache without throwing on empty caches", async () => {
    await expect(triggerLifecycle(listeners.install)).resolves.toBeUndefined();
  });
});

describe("service worker — policy constants", () => {
  it("uses the same 24h TTL as the client classifier", () => {
    // The SW source defines its own copy of the 24h constant for
    // isolation. This test pins the value match — drift would break the
    // pill's "may be outdated" copy aligning with the SW's stale flag.
    expect(STALENESS_THRESHOLD_MS).toBe(24 * 60 * 60 * 1000);
  });
});

describe("service worker — fetch handler", () => {
  function makeFetchEvent(request: Request): {
    event: FetchEvent;
    response: Promise<Response> | null;
  } {
    let captured: Promise<Response> | null = null;
    const event = {
      request,
      respondWith(promise: Promise<Response>) {
        captured = promise;
      },
    } as unknown as FetchEvent;
    return {
      event,
      get response() {
        return captured;
      },
    };
  }

  function invokeFetch(event: FetchEvent): void {
    for (const handler of listeners.fetch) {
      handler(event);
    }
  }

  it("ignores cross-origin requests", () => {
    const req = new Request("https://other.example/anything");
    const harness = makeFetchEvent(req);
    invokeFetch(harness.event);
    expect(harness.response).toBeNull();
  });

  it("ignores requests to /login (auth must always hit the network)", () => {
    const req = new Request("https://app.example/login");
    const harness = makeFetchEvent(req);
    invokeFetch(harness.event);
    expect(harness.response).toBeNull();
  });

  it("ignores non-cacheable GET paths like /random", () => {
    const req = new Request("https://app.example/random");
    const harness = makeFetchEvent(req);
    invokeFetch(harness.event);
    expect(harness.response).toBeNull();
  });

  it("intercepts /lots navigation requests", () => {
    const req = new Request("https://app.example/lots", {
      method: "GET",
    });
    // jsdom doesn't let us set request.mode; the SW checks
    // `request.mode === "navigate"` so we wrap with our own getter.
    Object.defineProperty(req, "mode", {
      configurable: true,
      get: () => "navigate",
    });
    // Mock fetch so the response promise resolves.
    const originalFetch = globalThis.fetch;
    globalThis.fetch = vi.fn().mockResolvedValue(
      new Response("<html>cached</html>", { status: 200 }),
    );
    const harness = makeFetchEvent(req);
    invokeFetch(harness.event);
    expect(harness.response).not.toBeNull();
    globalThis.fetch = originalFetch;
  });

  it("does NOT cache Convex query POSTs targeting auth functions", async () => {
    // A deactivated user's role payload could otherwise sit in cache for
    // up to 24h, defeating Story 1.3 deactivation. The SW must inspect
    // the request body's `path` field and bypass cache for any function
    // in AUTH_FUNCTION_PATHS (lib/auth:getCurrentUserOrNull,
    // users:getCurrentUserRoles, ...).
    const body = JSON.stringify({
      path: "lib/auth:getCurrentUserOrNull",
      args: {},
      format: "json",
    });
    const req = new Request("https://app.example/api/query", {
      method: "POST",
      body,
      headers: { "content-type": "application/json" },
    });

    // Reset the data cache so we can detect a write attempt.
    cacheRegistry.delete("cm-data-v1-dev");

    const originalFetch = globalThis.fetch;
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(JSON.stringify({ roles: ["admin"] }), {
        status: 200,
        headers: { "content-type": "application/json" },
      }),
    );
    globalThis.fetch = fetchMock;

    const harness = makeFetchEvent(req);
    invokeFetch(harness.event);
    expect(harness.response).not.toBeNull();
    const response = await harness.response!;
    expect(response.status).toBe(200);

    // Auth-skip path goes straight to fetch, no cache.put — confirm the
    // data cache was never populated for this request.
    const dataCache = cacheRegistry.get("cm-data-v1-dev");
    if (dataCache) {
      expect(dataCache.store.size).toBe(0);
    }
    expect(fetchMock).toHaveBeenCalled();

    globalThis.fetch = originalFetch;
  });

  it("caches Convex query POSTs for non-auth function paths", async () => {
    // Sanity check: a normal Convex query still goes through cache so
    // the auth-skip rule doesn't accidentally bypass caching for
    // everything.
    const body = JSON.stringify({
      path: "lots:listLots",
      args: {},
      format: "json",
    });
    const req = new Request("https://app.example/api/query", {
      method: "POST",
      body,
      headers: { "content-type": "application/json" },
    });

    cacheRegistry.delete("cm-data-v1-dev");

    const originalFetch = globalThis.fetch;
    globalThis.fetch = vi.fn().mockResolvedValue(
      new Response(JSON.stringify({ lots: [] }), {
        status: 200,
        headers: { "content-type": "application/json" },
      }),
    );

    const harness = makeFetchEvent(req);
    invokeFetch(harness.event);
    expect(harness.response).not.toBeNull();
    await harness.response!;

    const dataCache = cacheRegistry.get("cm-data-v1-dev");
    expect(dataCache).toBeDefined();
    expect(dataCache!.store.size).toBe(1);

    globalThis.fetch = originalFetch;
  });
});
