/**
 * Regenerate the PWA launcher icons from the canonical brand mark.
 *
 * `public/brand/mark.svg` is the one source of the logo — `BrandMark`
 * reads it directly, so the marketing site, nav and footer all follow a
 * change to that file with nothing else to edit.
 *
 * The launcher icons cannot: a manifest icon has to be a standalone
 * file at a fixed size with its own background, because a launcher
 * composites it onto whatever the wallpaper is and an emerald mark on a
 * dark wallpaper disappears. So they embed a copy of the mark's paths —
 * and a hand-kept copy of a logo drifts, with the one that drifts always
 * being the one nobody looks at.
 *
 * This makes the copy mechanical. Run it after changing `mark.svg`:
 *
 *     node scripts/build-icons.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MARK = path.join(ROOT, "public", "brand", "mark.svg");
const OUT_DIR = path.join(ROOT, "public", "icons");

/** Sizes the manifest asks for. */
const SIZES = [192, 512];

/**
 * How much of the tile the mark occupies.
 *
 * A launcher may mask the icon to a circle or a squircle. At 74% the
 * laurel's outer edge stays clear of every common mask.
 */
const MARK_FRACTION = 0.74;

/** The mark's own coordinate space. */
const MARK_W = 600;
const MARK_H = 535;

const BRAND_IVORY = "#F6F2EA";

function markBody() {
  const svg = readFileSync(MARK, "utf8").replace(/\r\n/g, "\n");
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  if (open === -1 || close === -1) {
    throw new Error("public/brand/mark.svg is not a well-formed <svg>");
  }
  return svg
    .slice(open + 1, close)
    // The icon supplies its own accessible name; the mark's would be a
    // second, competing one.
    .replace(/<title>[\s\S]*?<\/title>/g, "")
    .replace(/<desc>[\s\S]*?<\/desc>/g, "")
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => "      " + line.trim())
    .join("\n");
}

function icon(px, body) {
  const scale = (px * MARK_FRACTION) / MARK_W;
  const w = MARK_W * scale;
  const h = MARK_H * scale;
  const tx = ((px - w) / 2).toFixed(2);
  const ty = ((px - h) / 2).toFixed(2);
  const radius = Math.round(px * 0.1875);

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${px} ${px}" width="${px}" height="${px}" role="img" aria-label="Apostle Paul Memorial Park">
  <title>Apostle Paul Memorial Park</title>
  <!--
    GENERATED by scripts/build-icons.mjs from public/brand/mark.svg.
    Edit the mark, then re-run the script — changes here are lost.

    Ivory ground rather than transparent: a launcher composites the icon
    onto the wallpaper, and an emerald mark on a dark wallpaper vanishes.
  -->
  <rect width="${px}" height="${px}" rx="${radius}" fill="${BRAND_IVORY}"/>
  <g transform="translate(${tx} ${ty}) scale(${scale.toFixed(5)})">
${body}
  </g>
</svg>
`;
}

const body = markBody();
for (const px of SIZES) {
  const file = path.join(OUT_DIR, `icon-${px}.svg`);
  writeFileSync(file, icon(px, body), "utf8");
  console.log(`[build-icons] wrote ${path.relative(ROOT, file)}`);
}
