"use client";

/**
 * InstallmentSchedule — Story 3.4 (FR21).
 *
 * Read-only table that previews the schedule generated by
 * `generateInstallmentSchedule`. Lives in the SaleForm's Installment
 * tab below the contract-terms inputs; re-renders live as the user
 * types via React's normal render cycle (no `useMemo` needed — the
 * schedule generator is pure and cheap for N ≤ 60).
 *
 * Empty state: when `totalPriceCents <= downPaymentCents` or
 * `termMonths === 0`, render an instructional placeholder rather than
 * an empty table. No skeleton — this is informational, not
 * data-loading.
 *
 * Money / dates: every cents value renders via `formatPeso`; every
 * dueDate renders via `formatDate(ms, "short")` (Manila tz). The total
 * row at the bottom sums the rows' principals and is compared against
 * `totalPriceCents − downPaymentCents` in tests (NFR-M2 cents-precision).
 */

import { useMemo } from "react";

import { cn } from "@/lib/cn";
import { formatPeso } from "@/lib/money";
import { formatDate } from "@/lib/time";

import {
  generateInstallmentSchedule,
  type ScheduleResult,
} from "./generateSchedule";

export interface InstallmentScheduleProps {
  totalPriceCents: number;
  downPaymentCents: number;
  termMonths: number;
  firstDueDate: number | null;
}

interface DerivedSchedule {
  kind: "ok";
  schedule: ScheduleResult;
  totalCents: number;
}

/**
 * Long-form month-name list used for the clamp-warning UX. The warning
 * itemises which target months were shortened so the operator knows
 * exactly which rows are affected (e.g. "Feb 2026 was clamped to the
 * 28th from the 31st").
 */
const MONTH_NAMES_LONG = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

function ordinalSuffix(day: number): string {
  if (day >= 11 && day <= 13) return "th";
  switch (day % 10) {
    case 1:
      return "st";
    case 2:
      return "nd";
    case 3:
      return "rd";
    default:
      return "th";
  }
}

interface DerivedEmpty {
  kind: "empty";
  message: string;
}

interface DerivedError {
  kind: "error";
  message: string;
}

type Derived = DerivedSchedule | DerivedEmpty | DerivedError;

function deriveSchedule(props: InstallmentScheduleProps): Derived {
  if (
    !Number.isFinite(props.totalPriceCents) ||
    props.totalPriceCents <= 0 ||
    !Number.isFinite(props.downPaymentCents) ||
    !Number.isFinite(props.termMonths) ||
    props.termMonths <= 0 ||
    props.firstDueDate === null
  ) {
    return {
      kind: "empty",
      message:
        "Enter total price, term, and first due date to preview the schedule.",
    };
  }
  if (props.downPaymentCents >= props.totalPriceCents) {
    return {
      kind: "empty",
      message:
        "Down payment must be less than the total price. Use the Full Payment tab for a one-shot sale.",
    };
  }
  try {
    const schedule = generateInstallmentSchedule({
      totalPriceCents: props.totalPriceCents,
      downPaymentCents: props.downPaymentCents,
      termMonths: props.termMonths,
      firstDueDate: props.firstDueDate,
    });
    const totalCents = schedule.rows.reduce(
      (acc, row) => acc + row.principalCents,
      0,
    );
    return { kind: "ok", schedule, totalCents };
  } catch (err) {
    return {
      kind: "error",
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

export function InstallmentSchedule(props: InstallmentScheduleProps) {
  const { totalPriceCents, downPaymentCents, termMonths, firstDueDate } = props;
  const derived = useMemo(
    () =>
      deriveSchedule({
        totalPriceCents,
        downPaymentCents,
        termMonths,
        firstDueDate,
      }),
    [totalPriceCents, downPaymentCents, termMonths, firstDueDate],
  );

  if (derived.kind === "empty") {
    return (
      <div
        data-testid="installment-schedule-empty"
        className="rounded-md border border-dashed border-slate-300 bg-slate-50 px-4 py-6 text-center text-sm text-slate-500"
      >
        {derived.message}
      </div>
    );
  }
  if (derived.kind === "error") {
    return (
      <div
        role="alert"
        data-testid="installment-schedule-error"
        className="rounded-md border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800"
      >
        {derived.message}
      </div>
    );
  }
  const { schedule, totalCents } = derived;
  // Month-end clamp warning (Epic-3/4 adversarial-review HIGH fix).
  // When the source day-of-month is 29 / 30 / 31, advancing the date
  // calendar-aware lands on the last day of the shorter target month
  // (e.g. Jan 31 → Feb 28). The contract paperwork says "the 31st" but
  // the actual due date is the 28th — surface the discrepancy here so
  // the operator can re-confirm the date with the customer rather than
  // discovering it months later when the customer is confused about
  // why their February reminder fell on the 28th.
  const clampWarning =
    schedule.clampedRowIndices.length > 0
      ? (() => {
          const sourceDay = schedule.sourceDayOfMonth;
          const monthLabels = schedule.clampedRowIndices.map((idx) => {
            const row = schedule.rows[idx];
            if (row === undefined) return null;
            const d = new Date(row.dueDate);
            return `${MONTH_NAMES_LONG[d.getUTCMonth()]} ${d.getUTCFullYear()} (clamped to the ${d.getUTCDate()}${ordinalSuffix(d.getUTCDate())})`;
          }).filter((s): s is string => s !== null);
          return `Heads up: your first due date is the ${sourceDay}${ordinalSuffix(sourceDay)} of the month, but some months are shorter. The following due dates were clamped to the last day of those months: ${monthLabels.join("; ")}. Confirm the dates with the customer before saving.`;
        })()
      : null;
  return (
    <div className="space-y-2">
      {clampWarning !== null ? (
        <div
          role="alert"
          data-testid="installment-schedule-clamp-warning"
          className="rounded-md border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"
        >
          {clampWarning}
        </div>
      ) : null}
      <div className="overflow-hidden rounded-md border border-slate-200">
        <table
          data-testid="installment-schedule"
          className="min-w-full divide-y divide-slate-200 text-sm"
        >
          <thead className="bg-slate-50">
            <tr>
              <th
                scope="col"
                className="px-3 py-2 text-left text-xs font-medium uppercase tracking-wide text-slate-500"
              >
                #
              </th>
              <th
                scope="col"
                className="px-3 py-2 text-left text-xs font-medium uppercase tracking-wide text-slate-500"
              >
                Due date
              </th>
              <th
                scope="col"
                className="px-3 py-2 text-right text-xs font-medium uppercase tracking-wide text-slate-500"
              >
                Amount
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 bg-white">
            {schedule.rows.map((row) => (
              <tr
                key={row.installmentNumber}
                data-testid={`installment-row-${row.installmentNumber}`}
              >
                <td className="px-3 py-2 text-slate-700 tabular-nums">
                  {row.installmentNumber}
                </td>
                <td className="px-3 py-2 text-slate-700">
                  {formatDate(row.dueDate, "short")}
                </td>
                <td
                  className="px-3 py-2 text-right text-slate-900 tabular-nums"
                  data-testid={`installment-amount-${row.installmentNumber}`}
                >
                  {formatPeso(row.principalCents)}
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="bg-slate-50">
              <td
                colSpan={2}
                className={cn(
                  "px-3 py-2 text-right text-xs font-medium uppercase tracking-wide text-slate-500",
                )}
              >
                Schedule total
              </td>
              <td
                className="px-3 py-2 text-right text-sm font-semibold text-slate-900 tabular-nums"
                data-testid="installment-schedule-total"
              >
                {formatPeso(totalCents)}
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
      <p className="text-xs text-slate-500">
        Monthly amount: {formatPeso(schedule.monthlyAmountCents)}. Remainder
        centavos (if any) land on the final installment to keep the headline
        figure honest.
      </p>
    </div>
  );
}
