/**
 * The app's own name and face.
 *
 * The web manifest is the one piece of branding nobody looks at, because
 * it only shows up once somebody installs the app to a home screen — and
 * by then it is on their phone saying the wrong thing. It named a
 * different park in a different palette, and pointed at two placeholder
 * tiles reading "BH" on slate, months after a real mark existed.
 *
 * Nothing about that fails a build or a test run. It just quietly ships.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(__dirname, "../..");

function read(rel: string): string {
  return readFileSync(path.join(ROOT, rel), "utf8");
}

const manifest = JSON.parse(read("public/manifest.webmanifest")) as {
  name: string;
  short_name: string;
  description: string;
  theme_color: string;
  background_color: string;
  icons: Array<{ src: string; sizes: string }>;
};

/** The palette from the brand guide. */
const EMERALD = "#1D5C4D";
const IVORY = "#F6F2EA";

describe("what an installed app calls itself", () => {
  it("names the park, not the software house that built it", () => {
    expect(manifest.name).toMatch(/Apostle Paul/i);
    expect(manifest.short_name).toMatch(/Apostle Paul/i);
  });

  it("does not still say Broadheader anywhere", () => {
    // Broadheader builds it; the park is the client, and the icon on a
    // home screen belongs to the park.
    const blob = JSON.stringify(manifest);
    expect(blob).not.toMatch(/broadheader/i);
  });

  it("says where the park actually is", () => {
    // The brand document's "Bulacan" is stale; the park is in Aringay,
    // La Union.
    expect(manifest.description).toMatch(/Aringay/i);
    expect(manifest.description).not.toMatch(/Bulacan/i);
  });

  it("uses the brand palette, not the scaffold's slate", () => {
    expect(manifest.theme_color).toBe(EMERALD);
    expect(manifest.background_color).toBe(IVORY);
  });
});

describe("the launcher icons", () => {
  const icons = ["public/icons/icon-192.svg", "public/icons/icon-512.svg"];

  it("are no longer the BH placeholder", () => {
    for (const file of icons) {
      const svg = read(file);
      expect(svg).not.toMatch(/>BH</);
      expect(svg).not.toContain("#1e293b");
    }
  });

  it("carry the actual mark", () => {
    // The gold diamond inlay where the laurel stems cross is unique to
    // the real mark — a redrawn approximation would not have it.
    for (const file of icons) {
      expect(read(file)).toContain("#C9A96B");
      expect(read(file)).toContain(EMERALD);
    }
  });

  it("sit on the brand ground rather than transparency", () => {
    // A launcher composites onto the wallpaper. An emerald mark on a
    // dark wallpaper simply disappears.
    for (const file of icons) {
      expect(read(file)).toContain(IVORY);
    }
  });

  it("stay inside a launcher's rounded mask", () => {
    // The mark is scaled to 74% of the tile. Any transform that filled
    // the tile would have the laurel's outer edge clipped on Android.
    for (const file of icons) {
      const m = /scale\(([0-9.]+)\)/.exec(read(file));
      expect(m).not.toBeNull();
      const px = file.includes("192") ? 192 : 512;
      // 600 is the mark's own viewBox width.
      const occupied = (Number(m![1]) * 600) / px;
      expect(occupied).toBeLessThan(0.8);
      expect(occupied).toBeGreaterThan(0.6);
    }
  });

  it("match every size the manifest asks for", () => {
    // A manifest pointing at a file that is not there is an icon that
    // silently falls back to a screenshot of the page.
    for (const entry of manifest.icons) {
      const rel = "public" + entry.src;
      expect(() => read(rel)).not.toThrow();
      const px = entry.sizes.split("x")[0];
      expect(read(rel)).toContain(`viewBox="0 0 ${px} ${px}"`);
    }
  });

  it("are generated from the mark, and say so", () => {
    // They embed a copy of the mark's paths. A copy nobody knows is a
    // copy is a logo that drifts.
    for (const file of icons) {
      expect(read(file)).toMatch(/GENERATED by scripts\/build-icons\.mjs/);
    }
  });
});
